title: Ochre
description: Official site of musician and composer Christopher Leary.
author: ochremusic
url: http://ochremusic.com
baseurl:
logo: /assets/logo.png

excerpt_separator: <!--more-->
highlighter: rouge
permalink: /:year/:month/:day/:title/

paginate_path: /page/:num/
paginate: 10

twitter:
  username: ochremusic
facebook:
  app_id: 341352649553991
  publisher: 190149549210
  admins: 100000537844760

social:
  name: Ochre
  links:
    - https://twitter.com/ochremusic
    - https://www.facebook.com/ochremusic
    - http://soundcloud.com/ochre
    - https://ochre.bandcamp.com/
    - https://bandcamp.ochremusic.com/
    - https://www.youtube.com/user/ochremusic

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
      image: /assets/logo.png
  -
    scope:
      path: ""
      type: posts
    values:
      category: [Ochre]
      image: /assets/logo.png
      show_adverts: false
      layout: post
      published: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jemoji

include: ['_pages']

exclude:
  - "*.sh"
  - "*.rdb"
  - .DS_Store
  - bower_components/
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules/
  - package.json
  - src/
