title: Ochre
description: Music by Christopher Leary
author:
  name: Chris

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

excerpt_separator: <!--more-->

permalink:    /:year/:month/:title/
highlighter: rouge

gems: [jekyll-paginate]
paginate_path: "page:num"
paginate: 10
