title: Ochre
description: Music by Christopher Leary
author: Chris
url:

twitter:
  username: ochremusic

facebook:
  app_id:
  publisher: 190149549210
  admins: 100000537844760

google_site_verification:

excerpt_separator: <!--more-->
highlighter: rouge
permalink: /:year/:month/:title/

paginate_path: "page:num"
paginate: 10

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      category:

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed
