title: Ochre
description: Music by Christopher Leary
author: Chris
url: http://ochremusic.com
baseurl:

twitter:
  username: ochremusic

facebook:
  app_id:
  publisher: 190149549210
  admins: 100000537844760

excerpt_separator: <!--more-->
highlighter: rouge
permalink: /:year/:month/:day/:title/

paginate_path: "/page:num/"
paginate: 10

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      category:

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - sync.sh
  - upload.sh
